
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: titulo
email: correo
# > this means to ignore newlines until "baseurl:"
description: >
 info1 - info2 - info3 
baseurl: "" # the subpath of your site, e.g. /blog

url: "" # the base hostname & protocol for your site

movil: 666 333 111
fijo: 999 666 333

description2: Todos los derechos reservados

# Social media profiles - feel free to add more here
twitter_username: usuario_twitter 
github_username: usuario_github
facebook_username: usuario_facebook
#instagram_username: usuario_instabram
#stackoverflow_url: https://URL_stackoverflow
#googleplus_username: usuario_googleplus
#skype_username: usuario_skype
#linkedin_url: https://URL_linkedin

# Address information
address_street: calle
address_city: ciudad
address_state: provincia
address_zip: cpostal

# Build settings
markdown: kramdown
